//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;

using LinqToDB;
using LinqToDB.Common;
using LinqToDB.Data;
using LinqToDB.DataProvider.SqlServer;
using LinqToDB.Extensions;
using LinqToDB.Mapping;

namespace ImageStore.Models.LinqToDB
{
	/// <summary>
	/// Database       : u0718435_ImageStore2
	/// Data Source    : 31.31.196.202
	/// Server Version : 13.00.4224
	/// </summary>
	public partial class ImageStoreDB : DataConnection
	{
		public ITable<ChangeLocationHistory>    ChangeLocationHistories    { get { return this.GetTable<ChangeLocationHistory>(); } }
		public ITable<Double>                   Doubles                    { get { return this.GetTable<Double>(); } }
		public ITable<ElementConstraint>        ElementConstraints         { get { return this.GetTable<ElementConstraint>(); } }
		public ITable<FileDetail>               FileDetails                { get { return this.GetTable<FileDetail>(); } }
		public ITable<Folder>                   Folders                    { get { return this.GetTable<Folder>(); } }
		public ITable<FolderScanHistory>        FolderScanHistories        { get { return this.GetTable<FolderScanHistory>(); } }
		public ITable<ImageConstraint>          ImageConstraints           { get { return this.GetTable<ImageConstraint>(); } }
		public ITable<LoadConfig>               LoadConfigs                { get { return this.GetTable<LoadConfig>(); } }
		public ITable<Locaction>                Locactions                 { get { return this.GetTable<Locaction>(); } }
		public ITable<LocationType>             LocationTypes              { get { return this.GetTable<LocationType>(); } }
		public ITable<Permission>               Permissions                { get { return this.GetTable<Permission>(); } }
		public ITable<Project>                  Projects                   { get { return this.GetTable<Project>(); } }
		public ITable<Storage>                  Storages                   { get { return this.GetTable<Storage>(); } }
		public ITable<StorageType>              StorageTypes               { get { return this.GetTable<StorageType>(); } }
		public ITable<StorageUserHolderHistory> StorageUserHolderHistories { get { return this.GetTable<StorageUserHolderHistory>(); } }
		public ITable<Transfer>                 Transfers                  { get { return this.GetTable<Transfer>(); } }
		public ITable<User>                     Users                      { get { return this.GetTable<User>(); } }

		public ImageStoreDB()
		{
			InitDataContext();
			InitMappingSchema();
		}

		public ImageStoreDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
			InitMappingSchema();
		}

		partial void InitDataContext  ();
		partial void InitMappingSchema();

		#region FreeTextTable

		public class FreeTextKey<T>
		{
			public T   Key;
			public int Rank;
		}

		private static MethodInfo _freeTextTableMethod1 = typeof(ImageStoreDB).GetMethod("FreeTextTable", new Type[] { typeof(string), typeof(string) });

		[FreeTextTableExpression]
		public ITable<FreeTextKey<TKey>> FreeTextTable<TTable, TKey>(string field, string text)
		{
			return this.GetTable<FreeTextKey<TKey>>(
				this,
				_freeTextTableMethod1,
				field,
				text);
		}

		private static MethodInfo _freeTextTableMethod2 = 
			typeof(ImageStoreDB).GetMethods()
				.Where(m => m.Name == "FreeTextTable" &&  m.IsGenericMethod && m.GetParameters().Length == 2)
				.Where(m => m.GetParameters()[0].ParameterType.IsGenericTypeEx() && m.GetParameters()[0].ParameterType.GetGenericTypeDefinition() == typeof(Expression<>))
				.Where(m => m.GetParameters()[1].ParameterType == typeof(string))
				.Single();

		[FreeTextTableExpression]
		public ITable<FreeTextKey<TKey>> FreeTextTable<TTable, TKey>(Expression<Func<TTable,string>> fieldSelector, string text)
		{
			return this.GetTable<FreeTextKey<TKey>>(
				this,
				_freeTextTableMethod2,
				fieldSelector,
				text);
		}

		#endregion
	}

	[Table(Schema="dbo", Name="ChangeLocationHistory")]
	public partial class ChangeLocationHistory
	{
		[Column("ChangeLocationHistory_id"), PrimaryKey, Identity] public int      ChangeLocationHistoryId { get; set; } // int
		[Column("Storage_id"),               NotNull             ] public int      StorageId               { get; set; } // int
		[Column("Location_id"),              NotNull             ] public int      LocationId              { get; set; } // int
		[Column(),                           NotNull             ] public DateTime DateChange              { get; set; } // datetime

		#region Associations

		/// <summary>
		/// FK_ChangeLocationHistory_Location
		/// </summary>
		[Association(ThisKey="LocationId", OtherKey="LocationId", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="FK_ChangeLocationHistory_Location", BackReferenceName="ChangeLocationHistoryLocations")]
		public Locaction Location { get; set; }

		/// <summary>
		/// FK_ChangeLocationHistory_Storage
		/// </summary>
		[Association(ThisKey="StorageId", OtherKey="StorageId", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="FK_ChangeLocationHistory_Storage", BackReferenceName="ChangeLocationHistories")]
		public Storage Storage { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="Doubles")]
	public partial class Double
	{
		[Column("FileDoubles_id"), Identity] public int    FileDoublesId { get; set; } // int
		[Column("FileDetail_id"),  NotNull ] public int    FileDetailId  { get; set; } // int
		[Column(),                 NotNull ] public string TransferName  { get; set; } // nvarchar(255)
		[Column("Storage_id"),     NotNull ] public int    StorageId     { get; set; } // int

		#region Associations

		/// <summary>
		/// FK_Doubles_FileDetail
		/// </summary>
		[Association(ThisKey="FileDetailId", OtherKey="FileDetailId", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="FK_Doubles_FileDetail", BackReferenceName="Doubles")]
		public FileDetail FileDetail { get; set; }

		/// <summary>
		/// FK_Doubles_Storage
		/// </summary>
		[Association(ThisKey="StorageId", OtherKey="StorageId", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="FK_Doubles_Storage", BackReferenceName="Doubles")]
		public Storage Storage { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="ElementConstraints")]
	public partial class ElementConstraint
	{
		[Column("ElementConstraint_id"), PrimaryKey,  NotNull] public int    ElementConstraintId { get; set; } // int
		[Column("FileStructElement_id"),              NotNull] public int    FileStructElementId { get; set; } // int
		[Column(),                                    NotNull] public int    ConstraintType      { get; set; } // int
		[Column(),                          Nullable         ] public string First               { get; set; } // nvarchar(255)
		[Column(),                          Nullable         ] public string Last                { get; set; } // nvarchar(255)
		[Column(),                          Nullable         ] public string RegEx               { get; set; } // nvarchar(1000)
		[Column(),                          Nullable         ] public string ElementValue        { get; set; } // nvarchar(255)
		[Column(),                          Nullable         ] public string ConstraintName      { get; set; } // nvarchar(255)
	}

	[Table(Schema="dbo", Name="FileDetail")]
	public partial class FileDetail
	{
		[Column("FileDetail_id"),        PrimaryKey, Identity] public int    FileDetailId        { get; set; } // int
		[Column("FolderScanHistory_id"), NotNull             ] public int    FolderScanHistoryId { get; set; } // int
		[Column("Folder_id"),            NotNull             ] public int    FolderId            { get; set; } // int
		[Column(),                       NotNull             ] public string ExtensionName       { get; set; } // nvarchar(50)
		[Column(),                       NotNull             ] public int    FileCount           { get; set; } // int
		[Column(),                       NotNull             ] public long   FileSize            { get; set; } // bigint

		#region Associations

		/// <summary>
		/// FK_Doubles_FileDetail_BackReference
		/// </summary>
		[Association(ThisKey="FileDetailId", OtherKey="FileDetailId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<Double> Doubles { get; set; }

		/// <summary>
		/// FK_FileDetail_Folder
		/// </summary>
		[Association(ThisKey="FolderScanHistoryId, FolderId", OtherKey="FolderScanHistoryId, FolderId", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="FK_FileDetail_Folder", BackReferenceName="FileDetails")]
		public Folder Folder { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="Folder")]
	public partial class Folder
	{
		[Column("FolderScanHistory_id"), PrimaryKey(1), NotNull] public int       FolderScanHistoryId { get; set; } // int
		[Column("Folder_id"),            PrimaryKey(2), NotNull] public int       FolderId            { get; set; } // int
		[Column("Storage_id"),                          NotNull] public int       StorageId           { get; set; } // int
		[Column(),                                      NotNull] public int       Lvl                 { get; set; } // int
		[Column(),                                      NotNull] public string    Name                { get; set; } // nvarchar(255)
		[Column(),                                      NotNull] public string    FolderPath          { get; set; } // nvarchar(255)
		[Column(),                                      NotNull] public int       TotalSubFolderCount { get; set; } // int
		[Column(),                          Nullable           ] public DateTime? DateDeleted         { get; set; } // datetime
		[Column(),                                      NotNull] public DateTime  DateAdded           { get; set; } // datetime
		[Column("ParentFolder_id"),         Nullable           ] public int?      ParentFolderId      { get; set; } // int
		[Column(),                          Nullable           ] public string    Paths               { get; set; } // nvarchar(255)

		#region Associations

		/// <summary>
		/// FK_FileDetail_Folder_BackReference
		/// </summary>
		[Association(ThisKey="FolderScanHistoryId, FolderId", OtherKey="FolderScanHistoryId, FolderId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<FileDetail> FileDetails { get; set; }

		/// <summary>
		/// FK_Folder_FolderScanHistory
		/// </summary>
		[Association(ThisKey="FolderScanHistoryId", OtherKey="FolderScanHistoryId", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="FK_Folder_FolderScanHistory", BackReferenceName="Folders")]
		public FolderScanHistory FolderScanHistory { get; set; }

		/// <summary>
		/// FK_Folder_Storage
		/// </summary>
		[Association(ThisKey="StorageId", OtherKey="StorageId", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="FK_Folder_Storage", BackReferenceName="Folders")]
		public Storage Storage { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="FolderScanHistory")]
	public partial class FolderScanHistory
	{
		[Column("FolderScanHistory_id"), PrimaryKey,  Identity] public int       FolderScanHistoryId            { get; set; } // int
		[Column(),                       NotNull              ] public DateTime  DateStartScan                  { get; set; } // datetime
		[Column(),                          Nullable          ] public DateTime? DateEndScan                    { get; set; } // datetime
		[Column("CreatorUser_id"),       NotNull              ] public int       CreatorUserId                  { get; set; } // int
		[Column(),                          Nullable          ] public string    DeleteScannedAfterCancellation { get; set; } // nvarchar(max)
		[Column("Transfer_id"),             Nullable          ] public int?      TransferId                     { get; set; } // int

		#region Associations

		/// <summary>
		/// FK_FolderScanHistory_User
		/// </summary>
		[Association(ThisKey="CreatorUserId", OtherKey="UserId", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="FK_FolderScanHistory_User", BackReferenceName="FolderScanHistories")]
		public User CreatorUser { get; set; }

		/// <summary>
		/// FK_Folder_FolderScanHistory_BackReference
		/// </summary>
		[Association(ThisKey="FolderScanHistoryId", OtherKey="FolderScanHistoryId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<Folder> Folders { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="ImageConstraints")]
	public partial class ImageConstraint
	{
		[Column("Transfer_id"),          PrimaryKey,  NotNull] public int    TransferId          { get; set; } // int
		[Column("FileStructElement_id"),              NotNull] public int    FileStructElementId { get; set; } // int
		[Column(),                          Nullable         ] public int?   Length              { get; set; } // int
		[Column(),                          Nullable         ] public int?   LenghtType          { get; set; } // int
		[Column(),                          Nullable         ] public int?   DPI                 { get; set; } // int
		[Column(),                          Nullable         ] public int?   Format              { get; set; } // int
		[Column(),                          Nullable         ] public string CompressionName     { get; set; } // nvarchar(50)
		[Column(),                          Nullable         ] public string RegEx               { get; set; } // nvarchar(1000)
		[Column(),                          Nullable         ] public bool?  IsOnlyNum           { get; set; } // bit
		[Column(),                          Nullable         ] public int?   JpegQuality         { get; set; } // int

		#region Associations

		/// <summary>
		/// FK_Transfers_ImageConstraints_BackReference
		/// </summary>
		[Association(ThisKey="TransferId", OtherKey="TransferId", CanBeNull=true, Relationship=Relationship.OneToOne, IsBackReference=true)]
		public Transfer Transfer { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="LoadConfigs")]
	public partial class LoadConfig
	{
		[Column("LoadConfig_id"), PrimaryKey,  Identity] public int    LoadConfigId    { get; set; } // int
		[Column("Project_id"),    NotNull              ] public int    ProjectId       { get; set; } // int
		[Column(),                   Nullable          ] public int?   FirstNum        { get; set; } // int
		[Column(),                   Nullable          ] public int?   LastNum         { get; set; } // int
		[Column(),                   Nullable          ] public bool?  EdgeBatchType   { get; set; } // bit
		[Column(),                   Nullable          ] public int?   EdgeLevel       { get; set; } // int
		[Column(),                   Nullable          ] public int?   MaxRecCount     { get; set; } // int
		[Column(),                   Nullable          ] public int?   GroupImgType    { get; set; } // int
		[Column(),                   Nullable          ] public string ImageTypeFilter { get; set; } // nvarchar(255)
		[Column(),                   Nullable          ] public string OrdinalFilter   { get; set; } // nvarchar(255)

		#region Associations

		/// <summary>
		/// FK_LoadConfigs_Projects
		/// </summary>
		[Association(ThisKey="ProjectId", OtherKey="ProjectId", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="FK_LoadConfigs_Projects", BackReferenceName="LoadConfigs")]
		public Project Project { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="Locaction")]
	public partial class Locaction
	{
		[Column("Location_id"),     PrimaryKey,  Identity] public int    LocationId     { get; set; } // int
		[Column(),                  NotNull              ] public string Name           { get; set; } // nvarchar(100)
		[Column(),                     Nullable          ] public string Description    { get; set; } // nvarchar(255)
		[Column("LocationType_id"),    Nullable          ] public int?   LocationTypeId { get; set; } // int

		#region Associations

		/// <summary>
		/// FK_ChangeLocationHistory_Location_BackReference
		/// </summary>
		[Association(ThisKey="LocationId", OtherKey="LocationId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<ChangeLocationHistory> ChangeLocationHistoryLocations { get; set; }

		/// <summary>
		/// FK_Locaction_LocationType
		/// </summary>
		[Association(ThisKey="LocationTypeId", OtherKey="LocationTypeId", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="FK_Locaction_LocationType", BackReferenceName="Locactions")]
		public LocationType LocationType { get; set; }

		/// <summary>
		/// FK_Storage_Locaction_BackReference
		/// </summary>
		[Association(ThisKey="LocationId", OtherKey="LocationId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<Storage> Storages { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="LocationType")]
	public partial class LocationType
	{
		[Column("LocationType_id"), PrimaryKey,  NotNull] public int    LocationTypeId { get; set; } // int
		[Column(),                               NotNull] public string Name           { get; set; } // nvarchar(50)
		[Column(),                     Nullable         ] public string Description    { get; set; } // nvarchar(255)

		#region Associations

		/// <summary>
		/// FK_Locaction_LocationType_BackReference
		/// </summary>
		[Association(ThisKey="LocationTypeId", OtherKey="LocationTypeId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<Locaction> Locactions { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="Permissions")]
	public partial class Permission
	{
		[Column("Permissions_id"), PrimaryKey, Identity] public int    PermissionsId   { get; set; } // int
		[Column(),                 Nullable            ] public string PermissionsName { get; set; } // nvarchar(255)

		#region Associations

		/// <summary>
		/// FK_User_Permissions_BackReference
		/// </summary>
		[Association(ThisKey="PermissionsId", OtherKey="PermissionsId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<User> Users { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="Projects")]
	public partial class Project
	{
		[Column("Project_id"),   PrimaryKey,  NotNull] public int    ProjectId    { get; set; } // int
		[Column(),                            NotNull] public string TransferName { get; set; } // nvarchar(255)
		[Column("Transfer_id"),               NotNull] public int    TransferId   { get; set; } // int
		[Column("Step_id"),         Nullable         ] public int?   StepId       { get; set; } // int
		[Column(),                  Nullable         ] public int?   Dept         { get; set; } // int
		[Column("Dept_Name"),       Nullable         ] public string DeptName     { get; set; } // nvarchar(255)
		[Column(),                  Nullable         ] public string DataSource   { get; set; } // nvarchar(255)
		[Column("Project_Name"),    Nullable         ] public string ProjectName  { get; set; } // nvarchar(255)
		[Column(),                  Nullable         ] public bool?  IsDefault    { get; set; } // bit
		[Column(),                  Nullable         ] public bool?  Enabled      { get; set; } // bit

		#region Associations

		/// <summary>
		/// FK_LoadConfigs_Projects_BackReference
		/// </summary>
		[Association(ThisKey="ProjectId", OtherKey="ProjectId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<LoadConfig> LoadConfigs { get; set; }

		/// <summary>
		/// FK_Projects_Transfers
		/// </summary>
		[Association(ThisKey="TransferId", OtherKey="TransferId", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="FK_Projects_Transfers", BackReferenceName="Projects")]
		public Transfer Transfer { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="Storage")]
	public partial class Storage
	{
		[Column("Storage_id"),           PrimaryKey,  NotNull] public int       StorageId           { get; set; } // int
		[Column("Project_id"),              Nullable         ] public int?      ProjectId           { get; set; } // int
		[Column(),                          Nullable         ] public string    Name                { get; set; } // nvarchar(255)
		[Column(),                          Nullable         ] public long?     TotalFreeSpace      { get; set; } // bigint
		[Column(),                                    NotNull] public long      TotalSize           { get; set; } // bigint
		[Column(),                          Nullable         ] public string    SerialNumber        { get; set; } // nvarchar(255)
		[Column(),                          Nullable         ] public DateTime? DateOfLastUpdate    { get; set; } // datetime
		[Column(),                                    NotNull] public DateTime  DateAdded           { get; set; } // datetime
		[Column(),                          Nullable         ] public string    Description         { get; set; } // nvarchar(255)
		[Column(),                          Nullable         ] public DateTime? DateDeleted         { get; set; } // datetime
		[Column("StorageType_id"),                    NotNull] public int       StorageTypeId       { get; set; } // int
		[Column("Location_id"),                       NotNull] public int       LocationId          { get; set; } // int
		[Column("OwnerUser_id"),                      NotNull] public int       OwnerUserId         { get; set; } // int
		[Column("CurrentHolderUser_id"),              NotNull] public int       CurrentHolderUserId { get; set; } // int

		#region Associations

		/// <summary>
		/// FK_ChangeLocationHistory_Storage_BackReference
		/// </summary>
		[Association(ThisKey="StorageId", OtherKey="StorageId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<ChangeLocationHistory> ChangeLocationHistories { get; set; }

		/// <summary>
		/// FK_Storage_User2
		/// </summary>
		[Association(ThisKey="CurrentHolderUserId", OtherKey="UserId", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="FK_Storage_User2", BackReferenceName="FkStorageUser2BackReferences")]
		public User CurrentHolderUser { get; set; }

		/// <summary>
		/// FK_Doubles_Storage_BackReference
		/// </summary>
		[Association(ThisKey="StorageId", OtherKey="StorageId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<Double> Doubles { get; set; }

		/// <summary>
		/// FK_Folder_Storage_BackReference
		/// </summary>
		[Association(ThisKey="StorageId", OtherKey="StorageId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<Folder> Folders { get; set; }

		/// <summary>
		/// FK_Storage_Locaction
		/// </summary>
		[Association(ThisKey="LocationId", OtherKey="LocationId", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="FK_Storage_Locaction", BackReferenceName="Storages")]
		public Locaction Location { get; set; }

		/// <summary>
		/// FK_Storage_User1
		/// </summary>
		[Association(ThisKey="OwnerUserId", OtherKey="UserId", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="FK_Storage_User1", BackReferenceName="StorageUsers")]
		public User OwnerUser { get; set; }

		/// <summary>
		/// FK_Storage_StorageType
		/// </summary>
		[Association(ThisKey="LocationId", OtherKey="StorageTypeId", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="FK_Storage_StorageType", BackReferenceName="Storages")]
		public StorageType StorageType { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="StorageType")]
	public partial class StorageType
	{
		[Column("StorageType_id"), PrimaryKey,  NotNull] public int    StorageTypeId { get; set; } // int
		[Column(),                              NotNull] public string Name          { get; set; } // nvarchar(255)
		[Column(),                    Nullable         ] public string Description   { get; set; } // nvarchar(255)

		#region Associations

		/// <summary>
		/// FK_Storage_StorageType_BackReference
		/// </summary>
		[Association(ThisKey="StorageTypeId", OtherKey="LocationId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<Storage> Storages { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="StorageUserHolderHistory")]
	public partial class StorageUserHolderHistory
	{
		[Column("StorageUserHolderHistory_id"), PrimaryKey, Identity] public int      StorageUserHolderHistoryId { get; set; } // int
		[Column("Storage_id"),                  NotNull             ] public int      StorageId                  { get; set; } // int
		[Column(),                              NotNull             ] public DateTime DateChange                 { get; set; } // datetime
		[Column("FromUser_id"),                 NotNull             ] public int      FromUserId                 { get; set; } // int
		[Column("ToUser_id"),                   NotNull             ] public int      ToUserId                   { get; set; } // int

		#region Associations

		/// <summary>
		/// FK_StorageUserHolderHistory_User_1
		/// </summary>
		[Association(ThisKey="FromUserId", OtherKey="UserId", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="FK_StorageUserHolderHistory_User_1", BackReferenceName="StorageUserHolderHistories")]
		public User FromUser { get; set; }

		/// <summary>
		/// FK_StorageUserHolderHistory_User_2
		/// </summary>
		[Association(ThisKey="ToUserId", OtherKey="UserId", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="FK_StorageUserHolderHistory_User_2", BackReferenceName="FkStorageUserHolderHistoryUser2BackReferences")]
		public User ToUser { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="Transfers")]
	public partial class Transfer
	{
		[Column("Transfer_id"), PrimaryKey,  Identity] public int       TransferId       { get; set; } // int
		[Column(),              NotNull              ] public string    TransferName     { get; set; } // nvarchar(255)
		[Column(),                 Nullable          ] public DateTime? DateRegistration { get; set; } // datetime
		[Column("User_id"),        Nullable          ] public string    UserId           { get; set; } // nvarchar(255)
		[Column(),                 Nullable          ] public int?      State            { get; set; } // int
		[Column(),                 Nullable          ] public DateTime? DatePartiton     { get; set; } // datetime
		[Column(),                 Nullable          ] public string    LoginPartition   { get; set; } // nvarchar(255)
		[Column(),                 Nullable          ] public string    CenterName       { get; set; } // nvarchar(255)
		[Column(),                 Nullable          ] public byte?     TransferType     { get; set; } // tinyint
		[Column(),              NotNull              ] public DateTime  VersionLoad      { get; set; } // date

		#region Associations

		/// <summary>
		/// FK_Projects_Transfers_BackReference
		/// </summary>
		[Association(ThisKey="TransferId", OtherKey="TransferId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<Project> Projects { get; set; }

		/// <summary>
		/// FK_Transfers_ImageConstraints
		/// </summary>
		[Association(ThisKey="TransferId", OtherKey="TransferId", CanBeNull=false, Relationship=Relationship.OneToOne, KeyName="FK_Transfers_ImageConstraints", BackReferenceName="Transfer")]
		public ImageConstraint Transfer_FK { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="User")]
	public partial class User
	{
		[Column("User_id"),        PrimaryKey,  Identity] public int      UserId                 { get; set; } // int
		[Column("Permissions_id"), NotNull              ] public int      PermissionsId          { get; set; } // int
		[Column(),                 NotNull              ] public string   Login                  { get; set; } // nvarchar(100)
		[Column(),                 NotNull              ] public DateTime DateAdded              { get; set; } // datetime
		[Column(),                    Nullable          ] public string   PasswordHash           { get; set; } // nchar(100)
		[Column(),                    Nullable          ] public string   FIO                    { get; set; } // nvarchar(100)
		[Column(),                    Nullable          ] public string   Post                   { get; set; } // nvarchar(100)
		[Column(),                    Nullable          ] public int?     RecipientAccessRequest { get; set; } // int
		[Column(),                    Nullable          ] public string   RequestAccess          { get; set; } // nchar(50)
		[Column(),                    Nullable          ] public string   Email                  { get; set; } // nchar(50)

		#region Associations

		/// <summary>
		/// FK_Storage_User2_BackReference
		/// </summary>
		[Association(ThisKey="UserId", OtherKey="CurrentHolderUserId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<Storage> FkStorageUser2BackReferences { get; set; }

		/// <summary>
		/// FK_StorageUserHolderHistory_User_2_BackReference
		/// </summary>
		[Association(ThisKey="UserId", OtherKey="ToUserId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<StorageUserHolderHistory> FkStorageUserHolderHistoryUser2BackReferences { get; set; }

		/// <summary>
		/// FK_FolderScanHistory_User_BackReference
		/// </summary>
		[Association(ThisKey="UserId", OtherKey="CreatorUserId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<FolderScanHistory> FolderScanHistories { get; set; }

		/// <summary>
		/// FK_User_Permissions
		/// </summary>
		[Association(ThisKey="PermissionsId", OtherKey="PermissionsId", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="FK_User_Permissions", BackReferenceName="Users")]
		public Permission Permission { get; set; }

		/// <summary>
		/// FK_StorageUserHolderHistory_User_1_BackReference
		/// </summary>
		[Association(ThisKey="UserId", OtherKey="FromUserId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<StorageUserHolderHistory> StorageUserHolderHistories { get; set; }

		/// <summary>
		/// FK_Storage_User1_BackReference
		/// </summary>
		[Association(ThisKey="UserId", OtherKey="OwnerUserId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<Storage> StorageUsers { get; set; }

		#endregion
	}

	public static partial class ImageStoreDBStoredProcedures
	{
		#region Find

		public static IEnumerable<FindResult> Find(this DataConnection dataConnection)
		{
			return dataConnection.QueryProc<FindResult>("[dbo].[Find]");
		}

		public partial class FindResult
		{
			public int       Storage_id          { get; set; }
			public string    Name                { get; set; }
			public string    FolderPath          { get; set; }
			public int       TotalSubFolderCount { get; set; }
			public DateTime? DateDeleted         { get; set; }
			public DateTime  DateAdded           { get; set; }
		}

		#endregion

		#region FindByDisk

		public static IEnumerable<FindByDiskResult> FindByDisk(this DataConnection dataConnection, int? @id)
		{
			return dataConnection.QueryProc<FindByDiskResult>("[dbo].[FindByDisk]",
				new DataParameter("@id", @id, DataType.Int32));
		}

		public partial class FindByDiskResult
		{
			public int       Storage_id          { get; set; }
			public string    FolderPath          { get; set; }
			public int       TotalSubFolderCount { get; set; }
			public DateTime? DateDeleted         { get; set; }
			public DateTime  DateAdded           { get; set; }
		}

		#endregion

		#region FindByPath

		public static IEnumerable<FindByPathResult> FindByPath(this DataConnection dataConnection, string @str)
		{
			return dataConnection.QueryProc<FindByPathResult>("[dbo].[FindByPath]",
				new DataParameter("@str", @str, DataType.NVarChar));
		}

		public partial class FindByPathResult
		{
			                         public string Path        { get; set; }
			[Column("Кол-во копий")] public int?   Кол_воКопий { get; set; }
			                         public int?   MaxId       { get; set; }
			                         public int?   MinId       { get; set; }
		}

		#endregion

		#region FindByPathAndStorageId

		public static IEnumerable<FindByPathAndStorageIdResult> FindByPathAndStorageId(this DataConnection dataConnection, string @str, int? @id)
		{
			return dataConnection.QueryProc<FindByPathAndStorageIdResult>("[dbo].[FindByPathAndStorageId]",
				new DataParameter("@str", @str, DataType.NVarChar),
				new DataParameter("@id",  @id,  DataType.Int32));
		}

		public partial class FindByPathAndStorageIdResult
		{
			                         public string Path        { get; set; }
			[Column("Кол-во копий")] public int?   Кол_воКопий { get; set; }
			                         public int?   MaxId       { get; set; }
			                         public int?   MinId       { get; set; }
		}

		#endregion
	}

	public static partial class TableExtensions
	{
		public static ChangeLocationHistory Find(this ITable<ChangeLocationHistory> table, int ChangeLocationHistoryId)
		{
			return table.FirstOrDefault(t =>
				t.ChangeLocationHistoryId == ChangeLocationHistoryId);
		}

		public static ElementConstraint Find(this ITable<ElementConstraint> table, int ElementConstraintId)
		{
			return table.FirstOrDefault(t =>
				t.ElementConstraintId == ElementConstraintId);
		}

		public static FileDetail Find(this ITable<FileDetail> table, int FileDetailId)
		{
			return table.FirstOrDefault(t =>
				t.FileDetailId == FileDetailId);
		}

		public static Folder Find(this ITable<Folder> table, int FolderScanHistoryId, int FolderId)
		{
			return table.FirstOrDefault(t =>
				t.FolderScanHistoryId == FolderScanHistoryId &&
				t.FolderId            == FolderId);
		}

		public static FolderScanHistory Find(this ITable<FolderScanHistory> table, int FolderScanHistoryId)
		{
			return table.FirstOrDefault(t =>
				t.FolderScanHistoryId == FolderScanHistoryId);
		}

		public static ImageConstraint Find(this ITable<ImageConstraint> table, int TransferId)
		{
			return table.FirstOrDefault(t =>
				t.TransferId == TransferId);
		}

		public static LoadConfig Find(this ITable<LoadConfig> table, int LoadConfigId)
		{
			return table.FirstOrDefault(t =>
				t.LoadConfigId == LoadConfigId);
		}

		public static Locaction Find(this ITable<Locaction> table, int LocationId)
		{
			return table.FirstOrDefault(t =>
				t.LocationId == LocationId);
		}

		public static LocationType Find(this ITable<LocationType> table, int LocationTypeId)
		{
			return table.FirstOrDefault(t =>
				t.LocationTypeId == LocationTypeId);
		}

		public static Permission Find(this ITable<Permission> table, int PermissionsId)
		{
			return table.FirstOrDefault(t =>
				t.PermissionsId == PermissionsId);
		}

		public static Project Find(this ITable<Project> table, int ProjectId)
		{
			return table.FirstOrDefault(t =>
				t.ProjectId == ProjectId);
		}

		public static Storage Find(this ITable<Storage> table, int StorageId)
		{
			return table.FirstOrDefault(t =>
				t.StorageId == StorageId);
		}

		public static StorageType Find(this ITable<StorageType> table, int StorageTypeId)
		{
			return table.FirstOrDefault(t =>
				t.StorageTypeId == StorageTypeId);
		}

		public static StorageUserHolderHistory Find(this ITable<StorageUserHolderHistory> table, int StorageUserHolderHistoryId)
		{
			return table.FirstOrDefault(t =>
				t.StorageUserHolderHistoryId == StorageUserHolderHistoryId);
		}

		public static Transfer Find(this ITable<Transfer> table, int TransferId)
		{
			return table.FirstOrDefault(t =>
				t.TransferId == TransferId);
		}

		public static User Find(this ITable<User> table, int UserId)
		{
			return table.FirstOrDefault(t =>
				t.UserId == UserId);
		}
	}
}

#pragma warning restore 1591
